name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.0.3
        with:
          aws-access-key-id: ${{ secrets.AKIA25Y6UDVOEYX6QTEH }}
          aws-secret-access-key: ${{ secrets.hXyUHqqhSzRMuobWnIMVAwoJdz7T/lbEGElGqU/X }}
          aws-region: ap-south-1

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: petclinicapp
          aws_region: ap-south-1
